<div class="span12">
    <div class="span12">
        <img src="/img/forum.png">
    </div>
    <div class="row-fluid">
        <div id="forum-table" class="span9">
        </div>
        <div class="span2">
            <div style="position:fixed" class="well span2">
                <p class="lead">If you would like to post in the forum, click here.</p>
                <a data-target="#post" role="button" data-toggle="modal" class="btn btn-large btn-primary posting"><i class="icon-comment icon-white"></i> Post</a>
            </div>
        </div>
    </div>
</div>

<div id="delete" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss"modal" aria-hidden"true">&times;</button>
        <h3>Delete post</h3>
    </div>
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete this post?</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <a id="delete_btn" class="btn btn-danger">Delete</a>
    </div>
</div>

<div id="post" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Forum Post</h3>
    </div>
    <div class="modal-body">
        <form class="form-horizontal" method="POST">
            <div class="control-group">
                <label for="title" class="control-label required">Title of Post</label>
                <div class="controls">
                    <input type="text" id="title" />
                </div>
            </div>
            <div class="control-group">
                <label for="name" class="control-label required">Your Name</label>
                <div class="controls">
                    <input type="text" id="name" />
                </div>
            </div>
            <div class="control-group">
                <label for="comment" class="control-label required">Post</label>
                <div class="controls">
                    <textarea style="height:50px" id="comment" ></textarea>
                </div>
            </div>
                
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button id="post_btn" class="btn btn-primary">Post</button>
    </div>
</div>

<script>
<?if(!$this->table):?>
    ForumTable.init('<?=$this->comments_json;?>')
<?endif;?>
$(document).on("click", ".deleting", function(){
    var to_delete = $(this).data('to_delete')
    $("#delete_btn").click(function(){
        params = {'id':to_delete}
        url = "/forum/delete-post"
        $.ajax({
            url: url,
            data: params,
            type: 'POST',
            success: function(){
                window.location.reload(true)
            }
        })
    })
})

$(document).on("click", ".posting", function(){
    var reply_to = $(this).data('reply_to')
    var title = $(this).data('title')
    if(title){
        $("#title").val('Re: '+title)
    }
    $("#post_btn").click(function(){
        alert('posting')
        var title = $("#title").val()
        var name = $("#name").val()
        var comment = $("#comment").val()
        
        if(!reply_to){
            reply_to = 0
        }
        
        params = {'title':title, 'name':name, 'comment':comment, 'reply_to':reply_to}
        url = "/forum/post";
        
        $.ajax({
            url: url,
            data: params,
            type: "POST",
            success: function(){
                window.location.reload(true)
            }
        })
    })
})
</script>