<div class="span12">
    <div class="span12">
        <img src="/img/photos.png">
    </div>
    <?if($this->logged_in):?>
    <div class="span12">
        <div class="alert alert-info">
            <h2>
                Hey <?=$this->user;?>!
                <a href="/photos/upload" class="btn btn-primary btn-large">Upload some photos</a>
            </h2>
        </div>
    </div>
    <?endif;?>
    <?if(!$this->images):?>
        <div class="hero-unit well">
            <h1>Images of trips coming soon...</h1>
        </div>
    <?else:?>
        <?$i = 1;?>
        <?foreach($this->images as $key => $image_group):?>
            <?if ($i > 1):?>
                <hr class="offset1" width="80%">
            <?endif;?>
            <div class="span12">
            <h1 class="offset1"><?=$key;?></h1>
            <div class="offset3 span8">
                <div class="slider-wrapper">
                    <div id="slider" class="slider nivoSlider">
                        <?foreach($image_group as $image):?>
                            <img src="/img/photos/<?=$image;?>">
                        <?endforeach;?>
                    </div>
                </div>
            </div>
            </div>
            <?$i++;?>
        <?endforeach;?>
    <?endif;?>
</div>

<script type="text/javascript">
$(window).load(function() {
    $('.slider').nivoSlider({
        pauseTime:6000,
    });
});
</script>