<div style="padding-top: 300px; background: url(/img/top_image.jpeg) center">
</div>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/home">Tufts Shred & Sled</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><a href="/home">Home</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/schedule">Schedule</a></li>
                    <li><a href="/music">Music</a></li>
                    <li><a href="/photos">Pictures</a></li>
                    <li><a href="/gear">Gear</a></li>
                    <li><a href="/forum">Forum</a></li>
                </ul>
            </div>
        </div>
    </div>    
</div>


<script type="text/javascript">
/*function woopraReady(tracker) {
    tracker.setDomain('thefrcp.com');
    tracker.setIdleTimeout(1800000);
    tracker.track();
    return false;
}
(function() {
    var wsc = document.createElement('script');
    wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
    wsc.type = 'text/javascript';
    wsc.async = true;
    var ssc = document.getElementsByTagName('script')[0];
    ssc.parentNode.insertBefore(wsc, ssc);
})();*/
</script>