<div class="span12">
  <div class="hero-unit well">
    <?if($this->show_errors):?>
      <h1>An error occurred</h1>
      <h2><?php echo $this->message ?></h2>
  
      <?php if (isset($this->exception)): ?>
      
      <h3>Exception information:</h3>
      <p>
          <b>Message:</b> <?php echo $this->exception->getMessage() ?>
      </p>
      
      <h3>Stack trace:</h3>
      <pre><?php echo $this->exception->getTraceAsString() ?>
      </pre>
    
      <h3>Request Parameters:</h3>
      <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
      </pre>
      <?endif;?>
    <?else:?>
      <h1>
        <div class="row-fluid">
          <div class="span4">
            <img src="/img/out_of_bounds.jpg">
          </div>
          404: Whoops... you've gone out of bounds. Here's a sweet video to make you feel better.
          <br><br>
          <div class="">
            <div class="video-wrapper2">
              <div class="video-container">
                <iframe src="http://player.vimeo.com/video/19289509?title=0&amp;byline=0&amp;portrait=0&amp;color=66b3ff" width="700" height="400" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
              </div>
            </div>
          </div>
        </div>
      </h1>
  
    <?php endif ?>
  </div>
</div>