<div class="span12">
    <div class="row-fluid">
        <div class="span8">
            <h1><img src="img/about_us.png"></h1>
            <br>
            <p class="lead">
                We are Tufts Undergrads who wanted to unite all the skiers and snowboarders on campus.  Want to hit the slopes but don't have a ride or anyone to go with?
                Well then check out the <a href="https://www.facebook.com/groups/375329062560837/" target="_blank">Facebook group</a> or the schedule for any upcoming trips or people looking for trips.
            </p>
        </div>
        <div class="">
            <img width="200" src="img/lm_park_logo.jpg">
            <img width="200" src="img/killington-logo.jpg">
        </div>
    </div>
    <div id="song" class="row-fluid">
    </div>
</div>


<script>
</script>