<div class="span12">
    <div class="row-fluid">
        <img class='span9' src="/img/music.png">
        <div class='span2'>
            <div style="position:fixed;" class='span2 alert alert-info'>
                <p style="font-size:14px">
                    Got some tunes you want to share?
                    Email <strong><a href="mailto:Aaron_B.Wishnick@tufts.edu?subject=Music Suggestions">Aaron_B.Wishnick@tufts.edu</a></strong> with your suggestions.
                </p>
            </div>
        </div>
    </div>
    <br>
    <div class="playlist ">
        <img class='' src="/img/aaron.png"><br>
        <div style="" class="offset1">
            <iframe src="http://8tracks.com/mixes/1182118/player_v3_universal" width="400" height="333.33" style="border: 0px none;"></iframe>
        </div>
    </div>
    <br>
    <div class="playlist ">
        <img class='' src="/img/nate.png"><br>
        <div style="" class="offset1">
        <iframe src="http://8tracks.com/mixes/1185288/player_v3_universal" width="400" height="333.33" style="border: 0px none;"></iframe>
        </div>
    </div>
    <br>
</div>
