<div class="pagination">
    <ul>
        <? for($i=1; $i <= $this->total_pages; $i++):
            if ($i == $this->page):?>
                <li class="active"><a ><?= $i; ?></a></li>
            <? else:?>
                <li><a onclick="ForumTable.show('<?= $i;?>');"><?= $i; ?></a></li>
            <? endif; ?>
        <? endfor; ?>
    </ul>
</div>
<?if($this->news):?>
    <?foreach($this->news as $news):?>
        <div class="well">
            <h2><?= date("l F jS, Y", strtotime($news['created']));?></h2>
            <p class="offset1 lead">
                <?= stripslashes($news['post']);?>
                <?if($news['quote'] != ""):?>
                    <br><br>
                    "<em><?=stripslashes($news['quote']);?></em>" -- <?=$news['quote_author'];?>
                <?endif;?>
            </p>
        </div>
    <?endforeach;?>
<?endif;?>
<div class="pagination">
    <ul>
        <? for($i=1; $i <= $this->total_pages; $i++):
            if ($i == $this->page):?>
                <li class="active"><a ><?= $i; ?></a></li>
            <? else:?>
                <li><a onclick="ForumTable.show('<?= $i;?>');"><?= $i; ?></a></li>
            <? endif; ?>
        <? endfor; ?>
    </ul>
</div>